In [1]:
val opNames = Array[String](
    "addr", "addi", "mulr", "muli", "banr", "bani", "borr", "bori", "setr", "seti", "gtir", "gtri", "gtrr", "eqir", "eqri", "eqrr")

opNames: Array[String] = Array(
  "addr",
  "addi",
  "mulr",
  "muli",
  "banr",
  "bani",
  "borr",
  "bori",
  "setr",
  "seti",
  "gtir",
  "gtri",
  "gtrr",
  "eqir",
...

In [2]:
case class Operation(before: Array[Int], opIndex: Int, a: Int, b: Int, output: Int)

object Operation {                  
    def apply(before: Array[Int], opString: String) : Operation = {
        val op = opString.split(' ')
        val opIO = op.tail.map(_ toInt)
        Operation(before, opNames.indexOf(op.head), opIO(0), opIO(1), opIO(2))
    }
    
    
}

defined class Operation
defined object Operation

In [3]:
def addr(op: Operation) : Int = op.before(op.a) + op.before(op.b)
def addi(op: Operation) : Int = op.before(op.a) + op.b
def mulr(op: Operation) : Int = op.before(op.a) * op.before(op.b)
def muli(op: Operation) : Int = op.before(op.a) * op.b
def banr(op: Operation) : Int = op.before(op.a) & op.before(op.b)
def bani(op: Operation) : Int = op.before(op.a) & op.b
def borr(op: Operation) : Int = op.before(op.a) | op.before(op.b)
def bori(op: Operation) : Int = op.before(op.a) | op.b
def setr(op: Operation) : Int = op.before(op.a)
def seti(op: Operation) : Int = op.a
def gtir(op: Operation) : Int = if (op.a > op.before(op.b)) 1 else 0
def gtri(op: Operation) : Int = if (op.before(op.a) > op.b) 1 else 0
def gtrr(op: Operation) : Int = if (op.before(op.a) > op.before(op.b)) 1 else 0
def eqir(op: Operation) : Int = if (op.a == op.before(op.b)) 1 else 0
def eqri(op: Operation) : Int = if (op.before(op.a) == op.b) 1 else 0
def eqrr(op: Operation) : Int = if (op.before(op.a) == op.before(op.b)) 1 else 0
val allOperations = Array[Operation => Int](
    addr, addi, mulr, muli, banr, bani, borr, bori, setr, seti, gtir, gtri, gtrr, eqir, eqri, eqrr)
// Taken from day 16 (not needed...)
val opsMap = Map(8 -> 13,11 -> 6,2 -> 5,5 -> 15,14 -> 4,13 -> 14,4 -> 12,7 -> 10,1 -> 9,10 -> 0,9 -> 2,3 -> 11,12 -> 7,15 -> 8,6 -> 1,0 -> 3)

defined function addr
defined function addi
defined function mulr
defined function muli
defined function banr
defined function bani
defined function borr
defined function bori
defined function setr
defined function seti
defined function gtir
defined function gtri
defined function gtrr
defined function eqir
defined function eqri
defined function eqrr
allOperations: Array[Operation => Int] = Array(
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
  <function1>,
...
opsMap: Map[Int, Int] = Map(
  0 -> 3,
  5 -> 15,
  10 -> 0,
  14 -> 4,
  1 -> 9,
  6 -> 1,
  9 -> 2,
  13 -> 14,
  2 -> 5,
  12 -> 7,
  7 -> 10,
  3 -> 11,
  11 -> 6,
  8 -> 13,
...

In [4]:
import scala.io.Source
import scala.collection.mutable.ListBuffer
val filename = "input"
val lines = Source.fromFile(filename).getLines.toList
val ip = lines.head.split(' ')(1).toInt
val registers = Array.fill(6)(0)
val program = lines.tail.toArray

import scala.io.Source
import scala.collection.mutable.ListBuffer
filename: String = "input"
lines: List[String] = List(
  "#ip 1",
  "addi 1 16 1",
  "seti 1 2 5",
  "seti 1 2 2",
  "mulr 5 2 3",
  "eqrr 3 4 3",
  "addr 3 1 1",
  "addi 1 1 1",
  "addr 5 0 0",
  "addi 2 1 2",
  "gtrr 2 4 3",
  "addr 1 3 1",
  "seti 2 8 1",
  "addi 5 1 5",
...
ip: Int = 1
registers: Array[Int] = Array(0, 0, 0, 0, 0, 0)
program: Array[String] = Array(
  "addi 1 16 1",
  "seti 1 2 5",
  "seti 1 2 2",
  "mulr 5 2 3",
  "eqrr 3 4 3",
  "addr 3 1 1",
  "addi 1 1 1",
  "addr 5 0 0",
  "addi 2 1 2",
  "gtrr 2 4 3",
  "addr 1 3 1",
  "seti 2 8 1",
  "addi 5 1 5",
  "gtrr 5 4 3",
...

In [5]:
var numInstructions = 0
println(registers.mkString(" "))
var halt = false
while (!halt) {
    val currentOperation = Operation(registers, program(registers(ip)))
    //println(opNames(currentOperation.opIndex), currentOperation.a, currentOperation.b, currentOperation.output)
    val output = allOperations(currentOperation.opIndex)(currentOperation)
    if (currentOperation.output == ip && output > program.length) {
        halt = true
    }
    else {
        registers(currentOperation.output) = output
    }
    if (registers(ip) < program.length-1 && !halt) {
        registers(ip) += 1
        numInstructions += 1
    }
    else {
        halt = true
    }
    //println(registers.mkString(" "))
}
println(numInstructions)
println(registers.mkString(" "))

0 0 0 0 0 0
6570323
1824 16 907 1 906 907


numInstructions: Int = 6570323
halt: Boolean = true

## Part 2

In [12]:
val registers = Array.fill(6)(0)
var numInstructions = 0
val reg0Set = scala.collection.mutable.Set(0)
println(registers.mkString(" "))
var halt = false
while (!halt) {
    val currentOperation = Operation(registers, program(registers(ip)))
    val output = allOperations(currentOperation.opIndex)(currentOperation)
    if (currentOperation.output == 0) {
        println(registers.mkString(" "))
        print(Seq(opNames(currentOperation.opIndex), 
                    currentOperation.a, 
                    currentOperation.b, 
                    currentOperation.output).mkString(", "))
        println(" = " + output)
        reg0Set += output
    }
    if (currentOperation.output == ip && output > program.length) {
        halt = true
    }
    else {
        registers(currentOperation.output) = output
    }
    if (registers(ip) < program.length-1 && !halt) {
        registers(ip) += 1
        numInstructions += 1
    }
    else {
        halt = true
    }
    // Inspect final 1000 instructions
    /*
    if (numInstructions > 6570323 - 10000) {
        println(Seq(opNames(currentOperation.opIndex), 
                    currentOperation.a, 
                    currentOperation.b, 
                    currentOperation.output).mkString(", "))
        println(registers.mkString(" "))
    }
    */
}
println(numInstructions)
println(registers.mkString(" "))
println(reg0Set.mkString(" "))

0 0 0 0 0 0
0 7 906 1 906 1
addr, 5, 0, 0 = 1
1 7 453 1 906 2
addr, 5, 0, 0 = 3
3 7 302 1 906 3
addr, 5, 0, 0 = 6
6 7 151 1 906 6
addr, 5, 0, 0 = 12
12 7 6 1 906 151
addr, 5, 0, 0 = 163
163 7 3 1 906 302
addr, 5, 0, 0 = 465
465 7 2 1 906 453
addr, 5, 0, 0 = 918
918 7 1 1 906 906
addr, 5, 0, 0 = 1824
6570323
1824 16 907 1 906 907
0 12 1 1824 6 3 918 163 465


registers: Array[Int] = Array(1824, 16, 907, 1, 906, 907)
numInstructions: Int = 6570323
reg0Set: collection.mutable.Set[Int] = Set(
  0,
  12,
  1,
  1824,
  6,
  3,
  918,
  163,
  465
)
halt: Boolean = true

Set of values in register 0 are common factors of initial large number (906 in this case) summed together as shown below

In [13]:
906 + 453 + 302 + 151 + 6 + 3 + 2 + 1
906/2
(453*2)/3
302/2
151
1*906
2*453
3*302
6*151
for (i <- 1 to 906) {
    if (906 % i == 0) {
        println(i + ": " + 906 % i)
    }
}

1: 0
2: 0
3: 0
6: 0
151: 0
302: 0
453: 0
906: 0


res12_0: Int = 1824
res12_1: Int = 453
res12_2: Int = 302
res12_3: Int = 151
res12_4: Int = 151
res12_5: Int = 906
res12_6: Int = 906
res12_7: Int = 906
res12_8: Int = 906

In [14]:
val registers = Array.fill(6)(0)
registers(0) = 1

registers: Array[Int] = Array(1, 0, 0, 0, 0, 0)

In [ ]:
var numInstructions = 0
val reg0Set = scala.collection.mutable.Set(0)
println(registers.mkString(" "))
var halt = false
while (!halt) {
    val currentOperation = Operation(registers, program(registers(ip)))
    val output = allOperations(currentOperation.opIndex)(currentOperation)
    if (currentOperation.output == 0) {
        println(registers.mkString(" "))
        print(Seq(opNames(currentOperation.opIndex), 
                    currentOperation.a, 
                    currentOperation.b, 
                    currentOperation.output).mkString(", "))
        println(" = " + output)
        reg0Set += output
    }
    if (currentOperation.output == ip && output > program.length) {
        halt = true
    }
    else {
        registers(currentOperation.output) = output
    }
    if (registers(ip) < program.length-1 && !halt) {
        registers(ip) += 1
        numInstructions += 1
    }
    else {
        halt = true
    }
    // Inspect final 1000 instructions
    /*
    if (numInstructions > 6570323 - 10000) {
        println(Seq(opNames(currentOperation.opIndex), 
                    currentOperation.a, 
                    currentOperation.b, 
                    currentOperation.output).mkString(", "))
        println(registers.mkString(" "))
    }
    */
}
println(numInstructions)
println(registers.mkString(" "))
println(reg0Set.mkString(" "))

1 0 0 0 0 0
1 34 0 10550400 10551306 0
seti, 0, 0, 0 = 0
0 7 10551306 1 10551306 1
addr, 5, 0, 0 = 1
1 7 5275653 1 10551306 2
addr, 5, 0, 0 = 3
3 7 3517102 1 10551306 3
addr, 5, 0, 0 = 6
6 7 1758551 1 10551306 6
addr, 5, 0, 0 = 12


In [32]:
906*2 + 16 - 4 

res31: Int = 1824

In [18]:
var numInstructions = 0
println(registers.mkString(" "))
var halt = false
while (!halt && numInstructions < 10000) {
    val currentOperation = Operation(registers, program(registers(ip)))
    println(opNames(currentOperation.opIndex), currentOperation.a, currentOperation.b, currentOperation.output)
    val output = allOperations(currentOperation.opIndex)(currentOperation)
    if (currentOperation.output == ip && output > program.length) {
        halt = true
    }
    else {
        registers(currentOperation.output) = output
    }
    if (registers(ip) < program.length-1 && !halt) {
        registers(ip) += 1
        numInstructions += 1
    }
    else {
        halt = true
    }
    println(registers.mkString(" "))
}
println(registers.mkString(" "))
println(numInstructions)

: 

In [17]:
10551306 + 5275653 + 3517102 + 1758551 // + ...
10551306/2
(5275653*2)/3
3517102/2
1758551/25
70342/2
(35171*2)/3
23447/2

res16_0: Int = 21102612
res16_1: Int = 5275653
res16_2: Int = 3517102
res16_3: Int = 1758551
res16_4: Int = 70342
res16_5: Int = 35171
res16_6: Int = 23447
res16_7: Int = 11723

After other experiments, can just work out factors of new large number (10551306)

In [16]:
val factors = scala.collection.mutable.Set[Int]()
for (i <- 1 to 10551306) {
    if (10551306 % i == 0) {
        factors += i
    }
}
factors.sum

factors: collection.mutable.Set[Int] = Set(
  1,
  2,
  89,
  3517102,
  3,
  118554,
  178,
  534,
  1758551,
  59277,
  267,
  6,
  19759,
  39518,
...
res14_2: Int = 21340800